name: auto-clang-format
on: 
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: clang-format
      uses: egor-tensin/clang-format@v1
      with:
        version: 16
        style: file
        exclude: ./lib/inja:./lib/url-matcher:./tests/Catch2
    - uses: EndBug/add-and-commit@v4
      with:
        author_name: Clang Robot
        author_email: robot@clang
        message: ':art: Committing clang-format changes'
        ref: ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}